events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        location /images/crypto/ {
            alias /usr/share/nginx/images/crypto/;
            try_files $uri =404;
        }

        location /images/fiat/ {
            alias /usr/share/nginx/images/fiat/;
            try_files $uri =404;
        }

        location / {
            return 404;
        }
    }
}