using Domain.Fiat;

namespace Domain.Currency.ValueObjects;

public class FiatNames
{
    private static readonly Dictionary<string, string> NamesEnglish = new Dictionary<
        string,
        string
    >()
    {
        { "AED", "United Arab Emirates Dirham" },
        { "AFN", "Afghan Afghani" },
        { "ALL", "Albanian Lek" },
        { "AMD", "Armenian Dram" },
        { "ANG", "Netherlands Antillean Guilder" },
        { "AOA", "Angolan Kwanza" },
        { "ARS", "Argentine Peso" },
        { "AUD", "Australian Dollar" },
        { "AWG", "Aruban Florin" },
        { "AZN", "Azerbaijani Manat" },
        { "BAM", "Bosnia and Herzegovina Convertible Mark" },
        { "BBD", "Barbadian Dollar" },
        { "BDT", "Bangladeshi Taka" },
        { "BGN", "Bulgarian Lev" },
        { "BHD", "Bahraini Dinar" },
        { "BIF", "Burundian Franc" },
        { "BMD", "Bermudian Dollar" },
        { "BND", "Brunei Dollar" },
        { "BOB", "Boliviano" },
        { "BRL", "Brazilian Real" },
        { "BSD", "Bahamian Dollar" },
        { "BTC", "Bitcoin" },
        { "BTN", "Bhutanese Ngultrum" },
        { "BWP", "Botswana Pula" },
        { "BYN", "Belarusian Ruble" },
        { "BZD", "Belize Dollar" },
        { "CAD", "Canadian Dollar" },
        { "CDF", "Congolese Franc" },
        { "CHF", "Swiss Franc" },
        { "CLF", "Chilean Unit of Account (UF)" },
        { "CLP", "Chilean Peso" },
        { "CNH", "Chinese Yuan (Offshore)" },
        { "CNY", "Chinese Yuan" },
        { "COP", "Colombian Peso" },
        { "CRC", "Costa Rican Colón" },
        { "CUC", "Cuban Convertible Peso" },
        { "CUP", "Cuban Peso" },
        { "CVE", "Cape Verdean Escudo" },
        { "CZK", "Czech Republic Koruna" },
        { "DJF", "Djiboutian Franc" },
        { "DKK", "Danish Krone" },
        { "DOP", "Dominican Peso" },
        { "DZD", "Algerian Dinar" },
        { "EGP", "Egyptian Pound" },
        { "ERN", "Eritrean Nakfa" },
        { "ETB", "Ethiopian Birr" },
        { "EUR", "Euro" },
        { "FJD", "Fijian Dollar" },
        { "FKP", "Falkland Islands Pound" },
        { "GBP", "British Pound Sterling" },
        { "GEL", "Georgian Lari" },
        { "GGP", "Guernsey Pound" },
        { "GHS", "Ghanaian Cedi" },
        { "GIP", "Gibraltar Pound" },
        { "GMD", "Gambian Dalasi" },
        { "GNF", "Guinean Franc" },
        { "GTQ", "Guatemalan Quetzal" },
        { "GYD", "Guyanese Dollar" },
        { "HKD", "Hong Kong Dollar" },
        { "HNL", "Honduran Lempira" },
        { "HRK", "Croatian Kuna" },
        { "HTG", "Haitian Gourde" },
        { "HUF", "Hungarian Forint" },
        { "IDR", "Indonesian Rupiah" },
        { "ILS", "Israeli New Shekel" },
        { "IMP", "Manx Pound" },
        { "INR", "Indian Rupee" },
        { "IQD", "Iraqi Dinar" },
        { "IRR", "Iranian Rial" },
        { "ISK", "Icelandic Króna" },
        { "JEP", "Jersey Pound" },
        { "JMD", "Jamaican Dollar" },
        { "JOD", "Jordanian Dinar" },
        { "JPY", "Japanese Yen" },
        { "KES", "Kenyan Shilling" },
        { "KGS", "Kyrgyzstani Som" },
        { "KHR", "Cambodian Riel" },
        { "KMF", "Comorian Franc" },
        { "KPW", "North Korean Won" },
        { "KRW", "South Korean Won" },
        { "KWD", "Kuwaiti Dinar" },
        { "KYD", "Cayman Islands Dollar" },
        { "KZT", "Kazakhstani Tenge" },
        { "LAK", "Lao Kip" },
        { "LBP", "Lebanese Pound" },
        { "LKR", "Sri Lankan Rupee" },
        { "LRD", "Liberian Dollar" },
        { "LSL", "Lesotho Loti" },
        { "LYD", "Libyan Dinar" },
        { "MAD", "Moroccan Dirham" },
        { "MDL", "Moldovan Leu" },
        { "MGA", "Malagasy Ariary" },
        { "MKD", "Macedonian Denar" },
        { "MMK", "Myanmar Kyat" },
        { "MNT", "Mongolian Tögrög" },
        { "MOP", "Macanese Pataca" },
        { "MRU", "Mauritanian Ouguiya" },
        { "MUR", "Mauritian Rupee" },
        { "MVR", "Maldivian Rufiyaa" },
        { "MWK", "Malawian Kwacha" },
        { "MXN", "Mexican Peso" },
        { "MYR", "Malaysian Ringgit" },
        { "MZN", "Mozambican Metical" },
        { "NAD", "Namibian Dollar" },
        { "NGN", "Nigerian Naira" },
        { "NIO", "Nicaraguan Córdoba" },
        { "NOK", "Norwegian Krone" },
        { "NPR", "Nepalese Rupee" },
        { "NZD", "New Zealand Dollar" },
        { "OMR", "Omani Rial" },
        { "PAB", "Panamanian Balboa" },
        { "PEN", "Peruvian Sol" },
        { "PGK", "Papua New Guinean Kina" },
        { "PHP", "Philippine Peso" },
        { "PKR", "Pakistani Rupee" },
        { "PLN", "Polish Złoty" },
        { "PYG", "Paraguayan Guaraní" },
        { "QAR", "Qatari Riyal" },
        { "RON", "Romanian Leu" },
        { "RSD", "Serbian Dinar" },
        { "RUB", "Russian Ruble" },
        { "RWF", "Rwandan Franc" },
        { "SAR", "Saudi Riyal" },
        { "SBD", "Solomon Islands Dollar" },
        { "SCR", "Seychellois Rupee" },
        { "SDG", "Sudanese Pound" },
        { "SEK", "Swedish Krona" },
        { "SGD", "Singapore Dollar" },
        { "SHP", "Saint Helena Pound" },
        { "SLL", "Sierra Leonean Leone" },
        { "SOS", "Somali Shilling" },
        { "SRD", "Surinamese Dollar" },
        { "SSP", "South Sudanese Pound" },
        { "STD", "São Tomé and Príncipe Dobra" },
        { "STN", "São Tomé and Príncipe Dobra" },
        { "SVC", "Salvadoran Colón" },
        { "SYP", "Syrian Pound" },
        { "SZL", "Swazi Lilangeni" },
        { "THB", "Thai Baht" },
        { "TJS", "Tajikistani Somoni" },
        { "TMT", "Turkmenistani Manat" },
        { "TND", "Tunisian Dinar" },
        { "TOP", "Tongan Paʻanga" },
        { "TRY", "Turkish Lira" },
        { "TTD", "Trinidad and Tobago Dollar" },
        { "TWD", "New Taiwan Dollar" },
        { "TZS", "Tanzanian Shilling" },
        { "UAH", "Ukrainian Hryvnia" },
        { "UGX", "Ugandan Shilling" },
        { "USD", "United States Dollar" },
        { "UYU", "Uruguayan Peso" },
        { "UZS", "Uzbekistani Som" },
        { "VES", "Venezuelan Bolívar Soberano" },
        { "VND", "Vietnamese đồng" },
        { "VUV", "Vanuatu Vatu" },
        { "WST", "Samoan Tala" },
        { "XAF", "Central African CFA Franc" },
        { "XAG", "Silver (troy ounce)" },
        { "XAU", "Gold (troy ounce)" },
        { "XCD", "East Caribbean Dollar" },
        { "XDR", "Special Drawing Rights" },
        { "XOF", "West African CFA Franc" },
        { "XPD", "Palladium (troy ounce)" },
        { "XPF", "CFP Franc" },
        { "XPT", "Platinum (troy ounce)" },
        { "YER", "Yemeni Rial" },
        { "ZAR", "South African Rand" },
        { "ZMW", "Zambian Kwacha" },
        { "ZWL", "Zimbabwean Dollar" }
    };

    private static readonly Dictionary<string, string> NamesRussian = new Dictionary<
        string,
        string
    >()
    {
        { "AED", "Дирхам Объединенных Арабских Эмиратов" },
        { "AFN", "Афгани" },
        { "ALL", "Албанский лек" },
        { "AMD", "Армянский драм" },
        { "ANG", "Нидерландский антильский гульден" },
        { "AOA", "Ангольская кванза" },
        { "ARS", "Аргентинское песо" },
        { "AUD", "Австралийский доллар" },
        { "AWG", "Арубанский флорин" },
        { "AZN", "Азербайджанский манат" },
        { "BAM", "Конвертируемая марка Боснии и Герцеговины" },
        { "BBD", "Барбадосский доллар" },
        { "BDT", "Бангладешская така" },
        { "BGN", "Болгарский лев" },
        { "BHD", "Бахрейнский динар" },
        { "BIF", "Бурундийский франк" },
        { "BMD", "Бермудский доллар" },
        { "BND", "Брунейский доллар" },
        { "BOB", "Боливиано" },
        { "BRL", "Бразильский реал" },
        { "BSD", "Багамский доллар" },
        { "BTC", "Биткойн" },
        { "BTN", "Бутанский нгултрум" },
        { "BWP", "Ботсванская пула" },
        { "BYN", "Белорусский рубль" },
        { "BZD", "Белизский доллар" },
        { "CAD", "Канадский доллар" },
        { "CDF", "Конголезский франк" },
        { "CHF", "Швейцарский франк" },
        { "CLF", "Чилийская единица счетов (UF)" },
        { "CLP", "Чилийское песо" },
        { "CNH", "Китайский юань (внебиржевой)" },
        { "CNY", "Китайский юань" },
        { "COP", "Колумбийское песо" },
        { "CRC", "Коста-риканский колон" },
        { "CUC", "Конвертируемое кубинское песо" },
        { "CUP", "Кубинское песо" },
        { "CVE", "Кабо-Верди эскудо" },
        { "CZK", "Чешская крона" },
        { "DJF", "Джибутийский франк" },
        { "DKK", "Датская крона" },
        { "DOP", "Доминиканское песо" },
        { "DZD", "Алжирский динар" },
        { "EGP", "Египетский фунт" },
        { "ERN", "Эритрейская накфа" },
        { "ETB", "Эфиопский быр" },
        { "EUR", "Евро" },
        { "FJD", "Фиджийский доллар" },
        { "FKP", "Фунт Фолклендских островов" },
        { "GBP", "Фунт стерлингов" },
        { "GEL", "Грузинский лари" },
        { "GGP", "Фунт Гернси" },
        { "GHS", "Ганский седи" },
        { "GIP", "Гибралтарский фунт" },
        { "GMD", "Гамбийская даласи" },
        { "GNF", "Гвинейский франк" },
        { "GTQ", "Гватемальский кетсаль" },
        { "GYD", "Гайанский доллар" },
        { "HKD", "Гонконгский доллар" },
        { "HNL", "Гондураская лемпира" },
        { "HRK", "Хорватская куна" },
        { "HTG", "Гаитянский гурд" },
        { "HUF", "Венгерский форинт" },
        { "IDR", "Индонезийская рупия" },
        { "ILS", "Новый израильский шекель" },
        { "IMP", "Манкс фунт" },
        { "INR", "Индийская рупия" },
        { "IQD", "Иракский динар" },
        { "IRR", "Иранский риал" },
        { "ISK", "Исландская крона" },
        { "JEP", "Фунт Джерси" },
        { "JMD", "Ямайский доллар" },
        { "JOD", "Иорданский динар" },
        { "JPY", "Японская иена" },
        { "KES", "Кенийский шиллинг" },
        { "KGS", "Киргизский сом" },
        { "KHR", "Камбоджийский риель" },
        { "KMF", "Коморский франк" },
        { "KPW", "Северокорейская вона" },
        { "KRW", "Южнокорейская вона" },
        { "KWD", "Кувейтский динар" },
        { "KYD", "Каймановый доллар" },
        { "KZT", "Казахстанский тенге" },
        { "LAK", "Лаосский кип" },
        { "LBP", "Ливанский фунт" },
        { "LKR", "Шри-ланкийская рупия" },
        { "LRD", "Либерийский доллар" },
        { "LSL", "Лесотский лоти" },
        { "LYD", "Ливийский динар" },
        { "MAD", "Марокканский дирхам" },
        { "MDL", "Молдавский лей" },
        { "MGA", "Малагасийский ариари" },
        { "MKD", "Македонский денар" },
        { "MMK", "Мьянманский кьят" },
        { "MNT", "Монгольский тугрик" },
        { "MOP", "Макао патака" },
        { "MRU", "Мавританская угия" },
        { "MUR", "Маврикийская рупия" },
        { "MVR", "Мальдивская руфия" },
        { "MWK", "Малавийская квача" },
        { "MXN", "Мексиканское песо" },
        { "MYR", "Малайзийский ринггит" },
        { "MZN", "Мозамбикский метикал" },
        { "NAD", "Намибийский доллар" },
        { "NGN", "Нигерийская найра" },
        { "NIO", "Никарагуанская кордоба" },
        { "NOK", "Норвежская крона" },
        { "NPR", "Непальская рупия" },
        { "NZD", "Новозеландский доллар" },
        { "OMR", "Оманский риал" },
        { "PAB", "Панамский бальбоа" },
        { "PEN", "Перуанский сол" },
        { "PGK", "Папуа – Новая Гвинея кина" },
        { "PHP", "Филиппинское песо" },
        { "PKR", "Пакистанская рупия" },
        { "PLN", "Польский злотый" },
        { "PYG", "Парагвайский гуарани" },
        { "QAR", "Катарский риял" },
        { "RON", "Румынский лей" },
        { "RSD", "Сербский динар" },
        { "RUB", "Российский рубль" },
        { "RWF", "Руандийский франк" },
        { "SAR", "Саудовский риял" },
        { "SBD", "Соломоновы Острова доллар" },
        { "SCR", "Сейшельская рупия" },
        { "SDG", "Суданский фунт" },
        { "SEK", "Шведская крона" },
        { "SGD", "Сингапурский доллар" },
        { "SHP", "Фунт Святой Елены" },
        { "SLL", "Сьерра-леонский леоне" },
        { "SOS", "Сомалийский шиллинг" },
        { "SRD", "Суринамский доллар" },
        { "SSP", "Южносуданский фунт" },
        { "STD", "Добра Сан-Томе и Принсипи" },
        { "STN", "Добра Сан-Томе и Принсипи" },
        { "SVC", "Сальвадорский колон" },
        { "SYP", "Сирийский фунт" },
        { "SZL", "Свазилендский лилангени" },
        { "THB", "Тайский бат" },
        { "TJS", "Таджикский сомони" },
        { "TMT", "Туркменский манат" },
        { "TND", "Тунисский динар" },
        { "TOP", "Тонгский паанга" },
        { "TRY", "Турецкая лира" },
        { "TTD", "Доллар Тринидада и Тобаго" },
        { "TWD", "Новый тайваньский доллар" },
        { "TZS", "Танзанийский шиллинг" },
        { "UAH", "Украинская гривна" },
        { "UGX", "Угандийский шиллинг" },
        { "USD", "Доллар США" },
        { "UYU", "Уругвайское песо" },
        { "UZS", "Узбекский сум" },
        { "VES", "Венесуэльский боливар собарно" },
        { "VND", "Вьетнамский донг" },
        { "VUV", "Вануату вату" },
        { "WST", "Самоанский тала" },
        { "XAF", "Центральноафриканский франк" },
        { "XAG", "Серебро (тройская унция)" },
        { "XAU", "Золото (тройская унция)" },
        { "XCD", "Восточно-карибский доллар" },
        { "XDR", "Специальные права заимствования" },
        { "XOF", "Западноафриканский франк" },
        { "XPD", "Палладий (тройская унция)" },
        { "XPF", "КФП франк" },
        { "XPT", "Платина (тройская унция)" },
        { "YER", "Йеменский риал" },
        { "ZAR", "Южноафриканский ранд" },
        { "ZMW", "Замбийская квача" },
        { "ZWL", "Зимбабвийский доллар" }
    };

    private static readonly Dictionary<string, string> NamesFrench = new Dictionary<
        string,
        string
    >()
    {
        { "AED", "Dirham des Émirats arabes unis" },
        { "AFN", "Afghani afghan" },
        { "ALL", "Lek albanais" },
        { "AMD", "Dram arménien" },
        { "ANG", "Florin antillais néerlandais" },
        { "AOA", "Kwanza angolais" },
        { "ARS", "Peso argentin" },
        { "AUD", "Dollar australien" },
        { "AWG", "Florin arubais" },
        { "AZN", "Manat azerbaïdjanais" },
        { "BAM", "Mark convertible de Bosnie-Herzégovine" },
        { "BBD", "Dollar barbadois" },
        { "BDT", "Taka bangladais" },
        { "BGN", "Lev bulgare" },
        { "BHD", "Dinar bahreïni" },
        { "BIF", "Franc burundais" },
        { "BMD", "Dollar bermudien" },
        { "BND", "Dollar brunéien" },
        { "BOB", "Boliviano" },
        { "BRL", "Réal brésilien" },
        { "BSD", "Dollar bahaméen" },
        { "BTC", "Bitcoin" },
        { "BTN", "Ngultrum bhoutanais" },
        { "BWP", "Pula botswanais" },
        { "BYN", "Rouble biélorusse" },
        { "BZD", "Dollar bélizien" },
        { "CAD", "Dollar canadien" },
        { "CDF", "Franc congolais" },
        { "CHF", "Franc suisse" },
        { "CLF", "Unité de compte chilienne (UF)" },
        { "CLP", "Peso chilien" },
        { "CNH", "Yuan chinois (offshore)" },
        { "CNY", "Yuan chinois" },
        { "COP", "Peso colombien" },
        { "CRC", "Colón costaricien" },
        { "CUC", "Peso convertible cubain" },
        { "CUP", "Peso cubain" },
        { "CVE", "Escudo du Cap-Vert" },
        { "CZK", "Couronne tchèque" },
        { "DJF", "Franc djiboutien" },
        { "DKK", "Couronne danoise" },
        { "DOP", "Peso dominicain" },
        { "DZD", "Dinar algérien" },
        { "EGP", "Livre égyptienne" },
        { "ERN", "Nakfa érythréen" },
        { "ETB", "Birr éthiopien" },
        { "EUR", "Euro" },
        { "FJD", "Dollar fidjien" },
        { "FKP", "Livre des îles Falkland" },
        { "GBP", "Livre sterling britannique" },
        { "GEL", "Lari géorgien" },
        { "GGP", "Livre de Guernesey" },
        { "GHS", "Cedi ghanéen" },
        { "GIP", "Livre de Gibraltar" },
        { "GMD", "Dalasi gambien" },
        { "GNF", "Franc guinéen" },
        { "GTQ", "Quetzal guatémaltèque" },
        { "GYD", "Dollar guyanais" },
        { "HKD", "Dollar de Hong Kong" },
        { "HNL", "Lempira hondurien" },
        { "HRK", "Kuna croate" },
        { "HTG", "Gourde haïtienne" },
        { "HUF", "Forint hongrois" },
        { "IDR", "Roupie indonésienne" },
        { "ILS", "Nouveau shekel israélien" },
        { "IMP", "Livre de l'Île de Man" },
        { "INR", "Roupie indienne" },
        { "IQD", "Dinar irakien" },
        { "IRR", "Rial iranien" },
        { "ISK", "Couronne islandaise" },
        { "JEP", "Livre de Jersey" },
        { "JMD", "Dollar jamaïcain" },
        { "JOD", "Dinar jordanien" },
        { "JPY", "Yen japonais" },
        { "KES", "Shilling kényan" },
        { "KGS", "SOM kirghize" },
        { "KHR", "Riel cambodgien" },
        { "KMF", "Franc comorien" },
        { "KPW", "Won nord-coréen" },
        { "KRW", "Won sud-coréen" },
        { "KWD", "Dinar koweïtien" },
        { "KYD", "Dollar des îles Caïmans" },
        { "KZT", "Tenge kazakh" },
        { "LAK", "Kip lao" },
        { "LBP", "Livre libanaise" },
        { "LKR", "Roupie srilankaise" },
        { "LRD", "Dollar libérien" },
        { "LSL", "Loti lesothan" },
        { "LYD", "Dinar libyen" },
        { "MAD", "Dirham marocain" },
        { "MDL", "Leu moldave" },
        { "MGA", "Ariary malgache" },
        { "MKD", "Dénar macédonien" },
        { "MMK", "Kyat birman" },
        { "MNT", "Tögrög mongol" },
        { "MOP", "Pataca macanaise" },
        { "MRU", "Ouguiya mauritanienne" },
        { "MUR", "Roupie mauricienne" },
        { "MVR", "Rufiyaa maldivienne" },
        { "MWK", "Kwacha malawienne" },
        { "MXN", "Peso mexicain" },
        { "MYR", "Ringgit malaisien" },
        { "MZN", "Métical mozambicain" },
        { "NAD", "Dollar namibien" },
        { "NGN", "Naira nigériane" },
        { "NIO", "Córdoba nicaraguayenne" },
        { "NOK", "Couronne norvégienne" },
        { "NPR", "Roupie népalaise" },
        { "NZD", "Dollar néo-zélandais" },
        { "OMR", "Rial omanais" },
        { "PAB", "Balboa panaméen" },
        { "PEN", "Sol péruvien" },
        { "PGK", "Kina papouan-néo-guinéen" },
        { "PHP", "Peso philippin" },
        { "PKR", "Roupie pakistanaise" },
        { "PLN", "Złoty polonais" },
        { "PYG", "Guaraní paraguayen" },
        { "QAR", "Riyal qatari" },
        { "RON", "Leu roumain" },
        { "RSD", "Dinar serbe" },
        { "RUB", "Rouble russe" },
        { "RWF", "Franc rwandais" },
        { "SAR", "Riyal saoudien" },
        { "SBD", "Dollar des îles Salomon" },
        { "SCR", "Roupie seychelloise" },
        { "SDG", "Livre soudanaise" },
        { "SEK", "Couronne suédoise" },
        { "SGD", "Dollar de Singapour" },
        { "SHP", "Livre de Sainte-Hélène" },
        { "SLL", "Leone sierra-léonais" },
        { "SOS", "Shilling somalien" },
        { "SRD", "Dollar surinamien" },
        { "SSP", "Livre sud-soudanaise" },
        { "STD", "Dobra de Sao Tomé-et-Principe" },
        { "STN", "Dobra de Sao Tomé-et-Principe" },
        { "SVC", "Colón salvadorien" },
        { "SYP", "Livre syrienne" },
        { "SZL", "Lilangeni swazi" },
        { "THB", "Baht thaïlandais" },
        { "TJS", "Somoni tadjik" },
        { "TMT", "Manat turkmène" },
        { "TND", "Dinar tunisien" },
        { "TOP", "Paʻanga tongien" },
        { "TRY", "Livre turque" },
        { "TTD", "Dollar de Trinité-et-Tobago" },
        { "TWD", "Nouveau dollar de Taïwan" },
        { "TZS", "Shilling tanzanien" },
        { "UAH", "Hryvnia ukrainienne" },
        { "UGX", "Shilling ougandais" },
        { "USD", "Dollar américain" },
        { "UYU", "Peso uruguayen" },
        { "UZS", "SOM ouzbek" },
        { "VES", "Bolívar souverain vénézuélien" },
        { "VND", "Dong vietnamien" },
        { "VUV", "Vatu vanuatais" },
        { "WST", "Tala samoan" },
        { "XAF", "Franc CFA d'Afrique centrale" },
        { "XAG", "Argent (once troy)" },
        { "XAU", "Or (once troy)" },
        { "XCD", "Dollar des Caraïbes orientales" },
        { "XDR", "Droits de tirage spéciaux" },
        { "XOF", "Franc CFA d'Afrique de l'Ouest" },
        { "XPD", "Palladium (once troy)" },
        { "XPF", "Franc CFP" },
        { "XPT", "Platinium (once troy)" },
        { "YER", "Rial yéménite" },
        { "ZAR", "Rand sud-africain" },
        { "ZMW", "Kwacha zambien" },
        { "ZWL", "Dollar zimbabwéen" }
    };

    private static readonly Dictionary<string, string> NamesGerman = new Dictionary<
        string,
        string
    >()
    {
        { "AED", "Dirham der Vereinigten Arabischen Emirate" },
        { "AFN", "Afghanischer Afghani" },
        { "ALL", "Albanischer Lek" },
        { "AMD", "Armenischer Dram" },
        { "ANG", "Niederländischer Antillen-Gulden" },
        { "AOA", "Angolanischer Kwanza" },
        { "ARS", "Argentinischer Peso" },
        { "AUD", "Australischer Dollar" },
        { "AWG", "Arubanischer Florin" },
        { "AZN", "Aserbaidschanischer Manat" },
        { "BAM", "Konvertierbare Mark von Bosnien und Herzegowina" },
        { "BBD", "Barbados-Dollar" },
        { "BDT", "Bangladesischer Taka" },
        { "BGN", "Bulgarischer Lew" },
        { "BHD", "Bahrainischer Dinar" },
        { "BIF", "Burundischer Franc" },
        { "BMD", "Bermuda-Dollar" },
        { "BND", "Brunei-Dollar" },
        { "BOB", "Boliviano" },
        { "BRL", "Brasilianischer Real" },
        { "BSD", "Bahama-Dollar" },
        { "BTC", "Bitcoin" },
        { "BTN", "Bhutanischer Ngultrum" },
        { "BWP", "Botswanischer Pula" },
        { "BYN", "Belarussischer Rubel" },
        { "BZD", "Belize-Dollar" },
        { "CAD", "Kanadischer Dollar" },
        { "CDF", "Kongo-Franc" },
        { "CHF", "Schweizer Franken" },
        { "CLF", "Chilenische Unidad de Fomento (UF)" },
        { "CLP", "Chilenischer Peso" },
        { "CNH", "Chinesischer Yuan (Offshore)" },
        { "CNY", "Chinesischer Yuan" },
        { "COP", "Kolumbianischer Peso" },
        { "CRC", "Costa Rica-Colón" },
        { "CUC", "Konvertibler Kubanischer Peso" },
        { "CUP", "Kubanischer Peso" },
        { "CVE", "Kap-Verde-Escudo" },
        { "CZK", "Tschechische Krone" },
        { "DJF", "Dschibuti-Franc" },
        { "DKK", "Dänische Krone" },
        { "DOP", "Dominikanischer Peso" },
        { "DZD", "Algerischer Dinar" },
        { "EGP", "Ägyptisches Pfund" },
        { "ERN", "Eritreische Nakfa" },
        { "ETB", "Äthiopischer Birr" },
        { "EUR", "Euro" },
        { "FJD", "Fidschi-Dollar" },
        { "FKP", "Falkland-Pfund" },
        { "GBP", "Britisches Pfund Sterling" },
        { "GEL", "Georgischer Lari" },
        { "GGP", "Guernsey-Pfund" },
        { "GHS", "Ghanaischer Cedi" },
        { "GIP", "Gibraltar-Pfund" },
        { "GMD", "Gambischer Dalasi" },
        { "GNF", "Guinea-Franc" },
        { "GTQ", "Guatemaltekischer Quetzal" },
        { "GYD", "Guyana-Dollar" },
        { "HKD", "Hongkong-Dollar" },
        { "HNL", "Honduranischer Lempira" },
        { "HRK", "Kroatische Kuna" },
        { "HTG", "Haitianischer Gourde" },
        { "HUF", "Ungarischer Forint" },
        { "IDR", "Indonesische Rupiah" },
        { "ILS", "Neuer Israelischer Schekel" },
        { "IMP", "Manx-Pfund" },
        { "INR", "Indische Rupie" },
        { "IQD", "Irakischer Dinar" },
        { "IRR", "Iranischer Rial" },
        { "ISK", "Isländische Krone" },
        { "JEP", "Jersey-Pfund" },
        { "JMD", "Jamaikanischer Dollar" },
        { "JOD", "Jordanischer Dinar" },
        { "JPY", "Japanischer Yen" },
        { "KES", "Kenia-Schilling" },
        { "KGS", "Kirgisischer Som" },
        { "KHR", "Kambodschanischer Riel" },
        { "KMF", "Komoren-Franc" },
        { "KPW", "Nordkoreanischer Won" },
        { "KRW", "Südkoreanischer Won" },
        { "KWD", "Kuwait-Dinar" },
        { "KYD", "Kaiman-Dollar" },
        { "KZT", "Kasachischer Tenge" },
        { "LAK", "Laotischer Kip" },
        { "LBP", "Libanesisches Pfund" },
        { "LKR", "Sri-Lanka-Rupie" },
        { "LRD", "Liberianischer Dollar" },
        { "LSL", "Lesothischer Loti" },
        { "LYD", "Libyscher Dinar" },
        { "MAD", "Marokkanischer Dirham" },
        { "MDL", "Moldawischer Leu" },
        { "MGA", "Madagaskar-Ariary" },
        { "MKD", "Mazedonischer Denar" },
        { "MMK", "Birmanischer Kyat" },
        { "MNT", "Mongolischer Tögrög" },
        { "MOP", "Macao-Pataca" },
        { "MRU", "Mauritanische Ouguiya" },
        { "MUR", "Mauritius-Rupie" },
        { "MVR", "Maldivische Rufiyaa" },
        { "MWK", "Malawischer Kwacha" },
        { "MXN", "Mexikanischer Peso" },
        { "MYR", "Malaysischer Ringgit" },
        { "MZN", "Mosambikanischer Metical" },
        { "NAD", "Namibischer Dollar" },
        { "NGN", "Nigerianischer Naira" },
        { "NIO", "Nicaragua-Córdoba" },
        { "NOK", "Norwegische Krone" },
        { "NPR", "Nepalesische Rupie" },
        { "NZD", "Neuseeland-Dollar" },
        { "OMR", "Omanischer Rial" },
        { "PAB", "Panamaischer Balboa" },
        { "PEN", "Peruanischer Sol" },
        { "PGK", "Papua-Neuguinea-Kina" },
        { "PHP", "Philippinischer Peso" },
        { "PKR", "Pakistanische Rupie" },
        { "PLN", "Polnischer Złoty" },
        { "PYG", "Paraguayanischer Guaraní" },
        { "QAR", "Katarischer Riyal" },
        { "RON", "Rumänischer Leu" },
        { "RSD", "Serbischer Dinar" },
        { "RUB", "Russischer Rubel" },
        { "RWF", "Ruanda-Franc" },
        { "SAR", "Saudi-Riyal" },
        { "SBD", "Salomonen-Dollar" },
        { "SCR", "Seychellen-Rupie" },
        { "SDG", "Sudanesisches Pfund" },
        { "SEK", "Schwedische Krone" },
        { "SGD", "Singapur-Dollar" },
        { "SHP", "Sankt Helena-Pfund" },
        { "SLL", "Sierra-Leone-Leone" },
        { "SOS", "Somalia-Schilling" },
        { "SRD", "Suriname-Dollar" },
        { "SSP", "Südsudan-Pfund" },
        { "STD", "São-Tomé-und-Príncipe-Dobra" },
        { "STN", "São-Tomé-und-Príncipe-Dobra" },
        { "SVC", "El-Salvador-Colón" },
        { "SYP", "Syrisches Pfund" },
        { "SZL", "Swasiland-Lilangeni" },
        { "THB", "Thailändischer Baht" },
        { "TJS", "Tadschikistan-Somoni" },
        { "TMT", "Turkmenistan-Manat" },
        { "TND", "Tunesischer Dinar" },
        { "TOP", "Tongaischer Paʻanga" },
        { "TRY", "Türkische Lira" },
        { "TTD", "Trinidad-und-Tobago-Dollar" },
        { "TWD", "Neuer Taiwan-Dollar" },
        { "TZS", "Tansania-Schilling" },
        { "UAH", "Ukrainische Hrywnja" },
        { "UGX", "Uganda-Schilling" },
        { "USD", "US-Dollar" },
        { "UYU", "Uruguayischer Peso" },
        { "UZS", "Usbekistan-Som" },
        { "VES", "Venezolanischer Bolívar Soberano" },
        { "VND", "Vietnamesischer Đồng" },
        { "VUV", "Vanuatu-Vatu" },
        { "WST", "Samoanischer Tala" },
        { "XAF", "CFA-Franc BEAC" },
        { "XAG", "Silber (Troy-Unze)" },
        { "XAU", "Gold (Troy-Unze)" },
        { "XCD", "Ostkaribischer Dollar" },
        { "XDR", "Sonderziehungsrechte" },
        { "XOF", "CFA-Franc BCEAO" },
        { "XPD", "Palladium (Troy-Unze)" },
        { "XPF", "CFP-Franc" },
        { "XPT", "Platin (Troy-Unze)" },
        { "YER", "Jemen-Rial" },
        { "ZAR", "Südafrikanischer Rand" },
        { "ZMW", "Sambia-Kwacha" },
        { "ZWL", "Simbabwe-Dollar" }
    };

    private static readonly Dictionary<string, string> NamesSpanish = new Dictionary<
        string,
        string
    >()
    {
        { "AED", "Dírham de los Emiratos Árabes Unidos" },
        { "AFN", "Afgani afgano" },
        { "ALL", "Lek albanés" },
        { "AMD", "Dram armenio" },
        { "ANG", "Florín antillano neerlandés" },
        { "AOA", "Kwanza angoleña" },
        { "ARS", "Peso argentino" },
        { "AUD", "Dólar australiano" },
        { "AWG", "Florín arubeño" },
        { "AZN", "Manat azerí" },
        { "BAM", "Marco convertible de Bosnia y Herzegovina" },
        { "BBD", "Dólar de Barbados" },
        { "BDT", "Taka de Bangladés" },
        { "BGN", "Lev búlgaro" },
        { "BHD", "Dinar bahreiní" },
        { "BIF", "Franco burundés" },
        { "BMD", "Dólar bermudeño" },
        { "BND", "Dólar de Brunéi" },
        { "BOB", "Boliviano" },
        { "BRL", "Real brasileño" },
        { "BSD", "Dólar bahameño" },
        { "BTC", "Bitcoin" },
        { "BTN", "Ngultrum de Bután" },
        { "BWP", "Pula de Botsuana" },
        { "BYN", "Rublo bielorruso" },
        { "BZD", "Dólar beliceño" },
        { "CAD", "Dólar canadiense" },
        { "CDF", "Franco congoleño" },
        { "CHF", "Franco suizo" },
        { "CLF", "Unidad de Fomento chilena (UF)" },
        { "CLP", "Peso chileno" },
        { "CNH", "Yuan chino (offshore)" },
        { "CNY", "Yuan chino" },
        { "COP", "Peso colombiano" },
        { "CRC", "Colón costarricense" },
        { "CUC", "Peso convertible cubano" },
        { "CUP", "Peso cubano" },
        { "CVE", "Escudo de Cabo Verde" },
        { "CZK", "Corona checa" },
        { "DJF", "Franco yibutiano" },
        { "DKK", "Corona danesa" },
        { "DOP", "Peso dominicano" },
        { "DZD", "Dinar argelino" },
        { "EGP", "Libra egipcia" },
        { "ERN", "Nakfa de Eritrea" },
        { "ETB", "Bir etíope" },
        { "EUR", "Euro" },
        { "FJD", "Dólar fiyiano" },
        { "FKP", "Libra de las Islas Malvinas" },
        { "GBP", "Libra esterlina" },
        { "GEL", "Lari georgiano" },
        { "GGP", "Libra de Guernsey" },
        { "GHS", "Cedi ghanés" },
        { "GIP", "Libra de Gibraltar" },
        { "GMD", "Dalasi gambiano" },
        { "GNF", "Franco guineano" },
        { "GTQ", "Quetzal guatemalteco" },
        { "GYD", "Dólar guyanés" },
        { "HKD", "Dólar de Hong Kong" },
        { "HNL", "Lempira hondureña" },
        { "HRK", "Kuna croata" },
        { "HTG", "Gourde haitiano" },
        { "HUF", "Forinto húngaro" },
        { "IDR", "Rupia indonesia" },
        { "ILS", "Nuevo shekel israelí" },
        { "IMP", "Libra de la Isla de Man" },
        { "INR", "Rupia india" },
        { "IQD", "Dinar iraquí" },
        { "IRR", "Rial iraní" },
        { "ISK", "Corona islandesa" },
        { "JEP", "Libra de Jersey" },
        { "JMD", "Dólar jamaicano" },
        { "JOD", "Dinar jordano" },
        { "JPY", "Yen japonés" },
        { "KES", "Chelín keniano" },
        { "KGS", "Som kirguís" },
        { "KHR", "Riel camboyano" },
        { "KMF", "Franco comorano" },
        { "KPW", "Won norcoreano" },
        { "KRW", "Won surcoreano" },
        { "KWD", "Dinar kuwaití" },
        { "KYD", "Dólar de las Islas Caimán" },
        { "KZT", "Tenge kazajo" },
        { "LAK", "Kip laosiano" },
        { "LBP", "Libra libanesa" },
        { "LKR", "Rupia de Sri Lanka" },
        { "LRD", "Dólar liberiano" },
        { "LSL", "Loti lesothense" },
        { "LYD", "Dinar libio" },
        { "MAD", "Dírham marroquí" },
        { "MDL", "Leu moldavo" },
        { "MGA", "Ariary malgache" },
        { "MKD", "Denar macedonio" },
        { "MMK", "Kyat birmano" },
        { "MNT", "Tugrik mongol" },
        { "MOP", "Pataca de Macao" },
        { "MRU", "Ouguiya mauritano" },
        { "MUR", "Rupia mauriciana" },
        { "MVR", "Rufiyaa maldiva" },
        { "MWK", "Kwacha malauí" },
        { "MXN", "Peso mexicano" },
        { "MYR", "Ringgit malasio" },
        { "MZN", "Metical mozambiqueño" },
        { "NAD", "Dólar namibio" },
        { "NGN", "Naira nigeriana" },
        { "NIO", "Córdoba nicaragüense" },
        { "NOK", "Corona noruega" },
        { "NPR", "Rupia nepalesa" },
        { "NZD", "Dólar neozelandés" },
        { "OMR", "Rial omaní" },
        { "PAB", "Balboa panameño" },
        { "PEN", "Sol peruano" },
        { "PGK", "Kina de Papúa Nueva Guinea" },
        { "PHP", "Peso filipino" },
        { "PKR", "Rupia paquistaní" },
        { "PLN", "Złoty polaco" },
        { "PYG", "Guaraní paraguayo" },
        { "QAR", "Riyal catarí" },
        { "RON", "Leu rumano" },
        { "RSD", "Dinar serbio" },
        { "RUB", "Rublo ruso" },
        { "RWF", "Franco ruandés" },
        { "SAR", "Riyal saudí" },
        { "SBD", "Dólar de las Islas Salomón" },
        { "SCR", "Rupia seychelense" },
        { "SDG", "Libra sudanesa" },
        { "SEK", "Corona sueca" },
        { "SGD", "Dólar de Singapur" },
        { "SHP", "Libra de Santa Elena" },
        { "SLL", "Leone de Sierra Leona" },
        { "SOS", "Chelín somalí" },
        { "SRD", "Dólar surinamés" },
        { "SSP", "Libra sudanesa del Sur" },
        { "STD", "Dobras de Santo Tomé y Príncipe" },
        { "STN", "Dobras de Santo Tomé y Príncipe" },
        { "SVC", "Colón salvadoreño" },
        { "SYP", "Libra siria" },
        { "SZL", "Lilangeni suazi" },
        { "THB", "Baht tailandés" },
        { "TJS", "Somoni tayiko" },
        { "TMT", "Manat turcomano" },
        { "TND", "Dinar tunecino" },
        { "TOP", "Paʻanga tongano" },
        { "TRY", "Lira turca" },
        { "TTD", "Dólar de Trinidad y Tobago" },
        { "TWD", "Nuevo dólar taiwanés" },
        { "TZS", "Chelín tanzano" },
        { "UAH", "Hryvnia ucraniana" },
        { "UGX", "Chelín ugandés" },
        { "USD", "Dólar estadounidense" },
        { "UYU", "Peso uruguayo" },
        { "UZS", "Som uzbeko" },
        { "VES", "Bolívar soberano venezolano" },
        { "VND", "Dong vietnamita" },
        { "VUV", "Vatu vanuatuense" },
        { "WST", "Tala samoano" },
        { "XAF", "Franco CFA de África Central" },
        { "XAG", "Plata (onza troy)" },
        { "XAU", "Oro (onza troy)" },
        { "XCD", "Dólar del Caribe Oriental" },
        { "XDR", "Derechos Especiales de Giro" },
        { "XOF", "Franco CFA de África Occidental" },
        { "XPD", "Paladio (onza troy)" },
        { "XPF", "Franco CFP" },
        { "XPT", "Platino (onza troy)" },
        { "YER", "Rial yemení" },
        { "ZAR", "Rand sudafricano" },
        { "ZMW", "Kwacha zambiano" },
        { "ZWL", "Dólar zimbabuense" }
    };

    private static readonly Dictionary<string, string> NamesChinese = new Dictionary<
        string,
        string
    >()
    {
        { "AED", "阿联酋迪拉姆" },
        { "AFN", "阿富汗尼" },
        { "ALL", "阿尔巴尼亚列克" },
        { "AMD", "亚美尼亚德拉姆" },
        { "ANG", "荷属安的列斯盾" },
        { "AOA", "安哥拉宽扎" },
        { "ARS", "阿根廷比索" },
        { "AUD", "澳大利亚元" },
        { "AWG", "阿鲁巴弗罗林" },
        { "AZN", "阿塞拜疆马纳特" },
        { "BAM", "波黑可兑换马克" },
        { "BBD", "巴巴多斯元" },
        { "BDT", "孟加拉塔卡" },
        { "BGN", "保加利亚列弗" },
        { "BHD", "巴林第纳尔" },
        { "BIF", "布隆迪法郎" },
        { "BMD", "百慕大元" },
        { "BND", "文莱元" },
        { "BOB", "玻利维亚诺" },
        { "BRL", "巴西雷亚尔" },
        { "BSD", "巴哈马元" },
        { "BTC", "比特币" },
        { "BTN", "不丹努尔特鲁姆" },
        { "BWP", "博茨瓦纳普拉" },
        { "BYN", "白俄罗斯卢布" },
        { "BZD", "伯利兹元" },
        { "CAD", "加拿大元" },
        { "CDF", "刚果法郎" },
        { "CHF", "瑞士法郎" },
        { "CLF", "智利账户单位（UF）" },
        { "CLP", "智利比索" },
        { "CNH", "人民币（离岸）" },
        { "CNY", "人民币" },
        { "COP", "哥伦比亚比索" },
        { "CRC", "哥斯达黎加科朗" },
        { "CUC", "古巴可兑换比索" },
        { "CUP", "古巴比索" },
        { "CVE", "佛得角埃斯库多" },
        { "CZK", "捷克克朗" },
        { "DJF", "吉布提法郎" },
        { "DKK", "丹麦克朗" },
        { "DOP", "多米尼加比索" },
        { "DZD", "阿尔及利亚第纳尔" },
        { "EGP", "埃及镑" },
        { "ERN", "厄立特里亚纳克法" },
        { "ETB", "埃塞俄比亚比尔" },
        { "EUR", "欧元" },
        { "FJD", "斐济元" },
        { "FKP", "福克兰群岛镑" },
        { "GBP", "英镑" },
        { "GEL", "格鲁吉亚拉里" },
        { "GGP", "根西镑" },
        { "GHS", "加纳塞地" },
        { "GIP", "直布罗陀镑" },
        { "GMD", "冈比亚达拉西" },
        { "GNF", "几内亚法郎" },
        { "GTQ", "危地马拉格查尔" },
        { "GYD", "圭亚那元" },
        { "HKD", "港币" },
        { "HNL", "洪都拉斯伦皮拉" },
        { "HRK", "克罗地亚库纳" },
        { "HTG", "海地古德" },
        { "HUF", "匈牙利福林" },
        { "IDR", "印度尼西亚卢比" },
        { "ILS", "新以色列谢克尔" },
        { "IMP", "曼岛镑" },
        { "INR", "印度卢比" },
        { "IQD", "伊拉克第纳尔" },
        { "IRR", "伊朗里亚尔" },
        { "ISK", "冰岛克朗" },
        { "JEP", "泽西镑" },
        { "JMD", "牙买加元" },
        { "JOD", "约旦第纳尔" },
        { "JPY", "日元" },
        { "KES", "肯尼亚先令" },
        { "KGS", "吉尔吉斯斯坦索姆" },
        { "KHR", "柬埔寨瑞尔" },
        { "KMF", "科摩罗法郎" },
        { "KPW", "朝鲜圆" },
        { "KRW", "韩元" },
        { "KWD", "科威特第纳尔" },
        { "KYD", "开曼群岛元" },
        { "KZT", "哈萨克斯坦坚戈" },
        { "LAK", "老挝基普" },
        { "LBP", "黎巴嫩镑" },
        { "LKR", "斯里兰卡卢比" },
        { "LRD", "利比里亚元" },
        { "LSL", "莱索托洛蒂" },
        { "LYD", "利比亚第纳尔" },
        { "MAD", "摩洛哥迪拉姆" },
        { "MDL", "摩尔多瓦列伊" },
        { "MGA", "马达加斯加阿里亚里" },
        { "MKD", "北马其顿第纳尔" },
        { "MMK", "缅甸元" },
        { "MNT", "蒙古图格里克" },
        { "MOP", "澳门元" },
        { "MRU", "毛里塔尼亚乌吉亚" },
        { "MUR", "毛里求斯卢比" },
        { "MVR", "马尔代夫拉菲亚" },
        { "MWK", "马拉维克瓦查" },
        { "MXN", "墨西哥比索" },
        { "MYR", "马来西亚林吉特" },
        { "MZN", "莫桑比克梅蒂卡尔" },
        { "NAD", "纳米比亚元" },
        { "NGN", "尼日利亚奈拉" },
        { "NIO", "尼加拉瓜科多巴" },
        { "NOK", "挪威克朗" },
        { "NPR", "尼泊尔卢比" },
        { "NZD", "新西兰元" },
        { "OMR", "阿曼里亚尔" },
        { "PAB", "巴拿马巴波亚" },
        { "PEN", "秘鲁索尔" },
        { "PGK", "巴布亚新几内亚基那" },
        { "PHP", "菲律宾比索" },
        { "PKR", "巴基斯坦卢比" },
        { "PLN", "波兰兹罗提" },
        { "PYG", "巴拉圭瓜拉尼" },
        { "QAR", "卡塔尔里亚尔" },
        { "RON", "罗马尼亚列伊" },
        { "RSD", "塞尔维亚第纳尔" },
        { "RUB", "俄罗斯卢布" },
        { "RWF", "卢旺达法郎" },
        { "SAR", "沙特里亚尔" },
        { "SBD", "所罗门群岛元" },
        { "SCR", "塞舌尔卢比" },
        { "SDG", "苏丹镑" },
        { "SEK", "瑞典克朗" },
        { "SGD", "新加坡元" },
        { "SHP", "圣赫勒拿镑" },
        { "SLL", "塞拉利昂利昂" },
        { "SOS", "索马里先令" },
        { "SRD", "苏里南元" },
        { "SSP", "南苏丹镑" },
        { "STD", "圣多美和普林西比多布拉（已更改为STN）" },
        { "STN", "圣多美和普林西比多布拉" },
        { "SVC", "萨尔瓦多科朗" },
        { "SYP", "叙利亚镑" },
        { "SZL", "斯威士兰里兰吉尼" },
        { "THB", "泰铢" },
        { "TJS", "塔吉克斯坦索莫尼" },
        { "TMT", "土库曼斯坦马纳特" },
        { "TND", "突尼斯第纳尔" },
        { "TOP", "汤加潘加" },
        { "TRY", "土耳其里拉" },
        { "TTD", "特立尼达和多巴哥元" },
        { "TWD", "新台币" },
        { "TZS", "坦桑尼亚先令" },
        { "UAH", "乌克兰格里夫纳" },
        { "UGX", "乌干达先令" },
        { "USD", "美元" },
        { "UYU", "乌拉圭比索" },
        { "UZS", "乌兹别克斯坦索姆" },
        { "VES", "委内瑞拉玻利瓦尔" },
        { "VND", "越南盾" },
        { "VUV", "瓦努阿图瓦图" },
        { "WST", "萨摩亚塔拉" },
        { "XAF", "中非法郎" },
        { "XAG", "白银（公制盎司）" },
        { "XAU", "黄金（公制盎司）" },
        { "XCD", "东加勒比元" },
        { "XDR", "特别提款权" },
        { "XOF", "西非法郎" },
        { "XPD", "钯金（公制盎司）" },
        { "XPF", "太平洋法郎" },
        { "XPT", "铂金（公制盎司）" },
        { "YER", "也门里亚尔" },
        { "ZAR", "南非兰特" },
        { "ZMW", "赞比亚克瓦查" },
        { "ZWL", "津巴布韦元" }
    };

    public static List<CurrencyName> GetByCode(string code)
    {
        string englishName =
            NamesEnglish.GetValueOrDefault(code)
            ?? throw new ArgumentException($"Currency name not found for code: {code}");

        string russianName =
            NamesRussian.GetValueOrDefault(code)
            ?? throw new ArgumentException($"Currency name not found for code: {code}");

        string frenchName =
            NamesFrench.GetValueOrDefault(code)
            ?? throw new ArgumentException($"Currency name not found for code: {code}");

        string germanName =
            NamesGerman.GetValueOrDefault(code)
            ?? throw new ArgumentException($"Currency name not found for code: {code}");

        string spanishName =
            NamesSpanish.GetValueOrDefault(code)
            ?? throw new ArgumentException($"Currency name not found for code: {code}");

        string chineseName =
            NamesChinese.GetValueOrDefault(code)
            ?? throw new ArgumentException($"Currency name not found for code: {code}");

        return
        [
            new CurrencyName(englishName, "en"),
            new CurrencyName(russianName, "ru"),
            new CurrencyName(frenchName, "fr"),
            new CurrencyName(germanName, "de"),
            new CurrencyName(spanishName, "es"),
            new CurrencyName(chineseName, "zh")
        ];
    }

    public static string GetName(string code, string language)
    {
        string? name = GetByCode(code).FirstOrDefault(x => x.Language == language)?.Value;
        if (name == null)
            throw new Exception("Incorrect code or language arguments");

        return name;
    }
}
